### PR TITLE
Use .md in place of HTML for photography page

### PR DESCRIPTION
**Pull request by ascott1**
This pull request...
- Changes the markdown parser to Kramdown
- Replaces the photography.html page with a markdown version
- Fixes the broken Grunt watch task

### CODE REVIEW

**Comment by Scotchester** [comment]
Sweet :+1: 

Hey @davidakennedy and @danny8000, check this out. Switching to Kramdown with the options set here lets us use `div`s to set up grids in the content area.

**Comment by danny8000** [comment]
Hey, how come Adam's pull requests get merged right away! :)

Just when I feel that I am catching up to you guys (grunt, node, bower, redcarpet, etc.) you find something new...

Kramdown looks very cool, just read the docs, great solution. (I still don't think HTML is that hard, but I guess md is hip-er.)

PS: Thanks for fixing my watch task. I like this collaborative coding stuff!

**Comment by Scotchester** [comment]
Because the're 1/20th the size of yours? ;)

**Comment by danny8000** [comment]
I think it is because my pull request are riddled with bugs!

**Comment by ascott1** [comment]
@danny8000 the designers were looking for a way to quickly implement your sweet looking HTML'ized page on the other pages without having to convert everything to HTML, so I took a crack at this and showed it to them. I hope it makes it easier for all of us!

**Pull request merged**
