### PR TITLE
Update forms page to align with Capital Framework and cfgov-refresh

### PR DESCRIPTION
**Pull request by nataliafitzgerald**
## Goals: 
- [ ] Form fields are consistent across Capital Framework and cf-gov refresh
- [ ] Form fields specs are consistent in the Design Manual (and match what is built)
- [ ] Form fields are built to reflect our current color palette
- [ ] Form fields interactions are consistent across checkboxes, radio buttons, text input fields, drop downs, etc.

## Related issues: 
https://[GHE]/CFGOV/platform/issues/1085
https://[GHE]/CFGOV/platform/issues/1086

## Related docs: 
My fork of the forms page: 
http://nataliafitzgerald.github.io/design-manual/page-components/form-fields.html

Content doc: 
https://docs.google.com/document/d/1ZVJ-tgHo8oweVw4N5eitxMKIRLo9_s8qMuAoqN9YSMg/edit?userstoinvite=lorelei.kelly@collab.cfpb.gov&ts=598c7fcd

## Review
- @cfarm 
- @kurzn 
- @marteki 

[Preview this PR without the whitespace changes](?w=0)

## Notes
-

## Todos
-

## Checklist

* [ ] Changes are limited to a single goal (no scope creep)
* [ ] Code can be automatically merged (no conflicts)
* [ ] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
* [ ] Passes all existing automated tests
* [ ] New functions include new tests
* [ ] New functions are documented (with a description, list of inputs, and expected output)
* [ ] Placeholder code is flagged
* [ ] Visually tested in supported browsers and devices
* [ ] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)

### CODE REVIEW

**Comment by nataliafitzgerald** [comment]
@cfarm @marteki 
If we decide to move forward with calling this "Forms" instead of "Form fields" I may need a hand with changing the left nav.

**Comment by kurzn** [comment]
Looks good. One suggestion - create a new H3 sibling to Checkboxes called "Nested checkboxes" and move the usability content from Checkboxes referring to that under the new section and add the indeterminate states to it as well.

**Review by cfarm — APPROVED** [review]

**Review by kurzn — APPROVED** [review]
This looks good.

**Comment by nataliafitzgerald** [comment]
@cfarm - Can we merge?

**Pull request merged**
