### PR TITLE
Updated gem deps and instructions in readme for bundler

### PR DESCRIPTION
**Pull request by jimmynotjim**
Kramdown should be listed as a dependency to be installed by bundler. Bundler also requires `bundle exec` before ruby commands to work.

### CODE REVIEW

**Comment by jimmynotjim** [comment]
@Scotchester could you also test this one out? It'll make installing the project a lot easier for future folks.

**Comment by Scotchester** [comment]
Yep

**Comment by jimmynotjim** [comment]
@Scotchester Removed Kramdown after our discussion about .io site today. Seems to be working fine as long as you preface commands with `bundle exec`

**Comment by Scotchester** [comment]
Works! :+1:

**Pull request merged**
