### PR TITLE
added all beam content and images

### PR DESCRIPTION
**Pull request by mebates**

### CODE REVIEW

**Comment by Scotchester** [comment]
Cool cool. Just two bits of feedback before merging:
- Please add a blank line above each image tag.
- Please replace the existing degree symbols that didn't quite copy correctly from the PDF with (this whole string): `&deg;`

**Comment by mebates** [comment]
done! thanks for the feedback

**Comment by Scotchester** [comment]
You missed a degree symbol in the second paragraph :)

**Comment by mebates** [comment]
argh. now done

**Comment by Scotchester** [comment]
Thanks! Looking great now. Sorry for my nitpicking :)

**Pull request merged**
