### PR TITLE
Update grunt deps to latest

### PR DESCRIPTION
**Pull request by anselmbradford**
Inspired by updating autoprefixer so it prefixes the `appearance` CSS property so the select drop-downs aren't rounded on /page-components/form-fields.html.

## Changes

- Updates grunt dependencies to latest.
- Update node on Travis to 8.

## Testing

- `git checkout update_grunt`
- `npm install && grunt` should work.

## Notes

- This makes me realize in DM at least CF depends on the build process of where it's used. Maybe we need something like https://github.com/cfpb/AtomicComponent/pull/11 instead.

### CODE REVIEW

**Comment by anselmbradford** [comment]
Umm, any ideas on this? Travis is drunk:

```bash
npm ERR! peerinvalid The package grunt@1.0.1 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer grunt-autoprefixer@3.0.4 wants grunt@>=0.4.2
npm ERR! peerinvalid Peer grunt-banner@0.6.0 wants grunt@>=0.4.0
npm ERR! peerinvalid Peer grunt-contrib-concat@1.0.1 wants grunt@>=0.4.0
npm ERR! peerinvalid Peer load-grunt-tasks@3.5.2 wants grunt@>=0.4.0
npm ERR! peerinvalid Peer grunt-legacssy@0.4.0 wants grunt@~0.4.0
npm ERR! peerinvalid Peer grunt-contrib-jshint@1.1.0 wants grunt@>=0.4.0
npm ERR! peerinvalid Peer grunt-concurrent@2.3.1 wants grunt@>=0.4.0
```

**Comment by anselmbradford** [comment]
Figured it out, has to be newer node on Travis.

**Comment by Scotchester** [comment]
I've never seen this before:

```bash
Running "cssmin:main" (cssmin) task
>> Skipping remote @import of "//fast.fonts.net/t/1.css?apiType=css&projectid=44e8c964-4684-44c6-a6e3-3f3da8787b50" as no protocol given.
>> 1 file created. 187.58 kB → 144 kB
```

But the build completes fine.

**Comment by anselmbradford** [comment]
@Scotchester yeah just noticed that. Should I add `https:` to it?

**Comment by Scotchester** [comment]
@anselmbradford I dunno. I feel like if always using HTTPS were not a problem, we would have already done that.

**Comment by anselmbradford** [comment]
@Scotchester Try now, I followed https://stackoverflow.com/questions/21173522/cssmin-not-correctly-handling-import/28454233#28454233 in https://github.com/cfpb/design-manual/pull/528/commits/2e214dca654cf70a68409e9897f8129085dcd50e

**Comment by anselmbradford** [comment]
@Scotchester actually hold  up. That borks the css when running `npm start`.

**Comment by anselmbradford** [comment]
@Scotchester okay, I downgraded cssmin for now. Can you give it a try again? Thanks!

**Comment by Scotchester** [comment]
Looks good now!

**Review by Scotchester — APPROVED** [review]

**Pull request merged**
