### PR TITLE
Closes #215 & #203

### LINKED ISSUE #215: H6 on Print Typography Hierarchy example is incorrect
Avenir Medium 14/16 pt is correct. The example to the right is not; should be larger and not all caps.

### PR DESCRIPTION
**Pull request by iuloshi**
- Removed PDF link to Style Guide
- Fixed print type hierarchy examples on Typography page
- Added note in footer about why these styles are inconsistent with parts of cf.gov

### CODE REVIEW

**Comment by Scotchester** [comment]
Title casing the minicon section headings?

**Comment by iuloshi** [comment]
Yah, I didn't do that--I think it was from when I was fetching upstream.

**Comment by Scotchester** [comment]
Looks like there may be some other merge-revert issues, as well. I'll work with you to fix this up.

**Comment by iuloshi** [comment]
Closing this PR. Will re-fork and re-submit another PR.

**Pull request closed without merging**
