### PR TITLE
HOLD: Update color-principles.md

### PR DESCRIPTION
**Pull request by nataliafitzgerald**
Short description explaining the high-level reason for the pull request

## Additions

- Content changes/additions

## Removals

-

## Changes

-

## Testing

-

## Review

- @user

[Preview this PR without the whitespace changes](?w=0)

## Notes

-

## Todos

-

## Checklist

* [ ] Changes are limited to a single goal (no scope creep)
* [ ] Code can be automatically merged (no conflicts)
* [ ] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
* [ ] Passes all existing automated tests
* [ ] New functions include new tests
* [ ] New functions are documented (with a description, list of inputs, and expected output)
* [ ] Placeholder code is flagged
* [ ] Visually tested in supported browsers and devices
* [ ] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)

### CODE REVIEW

**Comment by ielerol** [comment]
The content changes make sense to us, but I think the sentence "Our color palette includes CFPB Green, white, black as well as eight supporting colors and their tints" should have an "and" in it. 

"Our color palette includes CFPB Green, white, and black, as well as eight supporting colors and their tints."

**Comment by TTylerCFPB** [comment]
When defining the core colors would it be useful to have hierarchy the CFPB Green takes precedence over the other defined colors?

**Comment by nataliafitzgerald** [comment]
**Next steps:** 
- Make content updates recommended by reviewers. 
- Add supporting text for the core colors. Emphasize the primary importance of brand green.
- Recommend continuing to include midtone (Green 60) and light tone (Green 20) in the core palette. This information is useful and helpful for designers and contractors - it's included in our logo and beam pattern and these are go-to colors in a simple brand piece where we just use text, the logo, and minimal visual elements (beam, logo, etc.).

**Comment by jenn-franklin** [comment]
+1 to "Recommend continuing to include midtone (Green 60) and light tone (Green 20) in the core palette." Agree that we're operating with assumptions of using these three hues as baselines. Also question if the gray used for the text of our logo should be part of our core colors. And am not sure that black should be in the core palette.

**Comment by jimmynotjim** [comment]
@nataliafitzgerald is this ready to be merged or did you have some updates to make?

**Comment by nataliafitzgerald** [comment]
@jimmynotjim 
We received some feedback from @huetingj and @TTylerCFPB about the core palette (and which colors should be included) as well as making sure we emphasize that our brand green is at the top of the color hierarchy. As a next step I'm going to try to come up with some possible approaches/options so that we can discuss as a larger GD team.

**Comment by Scotchester** [comment]
Any progress to report on this, @nataliafitzgerald?

**Comment by jimmynotjim** [comment]
If nothing else, we should merge it to keep it from getting stale, and assign an issue to address the missing bits. Better to be iterative and keep moving forward than lose steam and fall back.

**Comment by nataliafitzgerald** [comment]
@Scotchester @jimmynotjim 
I'll update the PR this week so that it reflects things that are resolved. At that point we can at least merge some changes and leave the rest for a future request.

**Comment by nataliafitzgerald** [comment]
I'm going to go ahead and close this PR since there are still unresolved issues about the primary color palette (and which colors should be included). At this point I will move discussion back to the color palette expansion issue. https://github.com/cfpb/design-manual/issues/327

**Pull request closed without merging**
