### PR TITLE
Update H4 on small screens

### PR DESCRIPTION
**Pull request by nataliafitzgerald**
## Additions
- Updated Heading 4 size for small screens 
  - 16px, Avenir Next, Medium / 18px line height
- Added small screen typography specs for all web heading levels 

## Removals
- Global: Removed space between value and "px"
- Global: Removed space between value and "pt"

## Changes
-

## Testing
-

## Review
- @marteki @Scotchester @huetingj 

[Preview this PR without the whitespace changes](?w=0)

## Screenshots
artboard 2

## Notes

-

## Todos

-

## Checklist

* [ ] Changes are limited to a single goal (no scope creep)
* [ ] Code can be automatically merged (no conflicts)
* [ ] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
* [ ] Passes all existing automated tests
* [ ] New functions include new tests
* [ ] New functions are documented (with a description, list of inputs, and expected output)
* [ ] Placeholder code is flagged
* [ ] Visually tested in supported browsers and devices
* [ ] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)

### CODE REVIEW

**Comment by marteki** [comment]
Looks like the Travis build is failing, from the same things I encountered on #593. Once that is accepted and merged, it should fix the fail that's blocking a merge.

**Review by marteki — CHANGES_REQUESTED** [review]
Looks good for the typography changes. Is there anyway we could define what we mean by a "small screen", or link to a definition we have elsewhere on the manual?

If it's screens below a certain pixel width, we should state that so it's not as subject to interpretation or confusion.

**Comment by nataliafitzgerald** [comment]
@marteki - Updated to "Small screens:" to "<601px wide:" as a patch pending further discussion on how we can be more consistent across the DM in terms of how we talk about responsive sizes. 

screencapture-0-0-0-0-4000-brand-guidelines-typography-html-1519248098204

**Review by marteki — APPROVED** [review]

**Comment by jenn-franklin** [comment]
I can understand the need to define "small screen." Instead of including pixels here, could we jump link to "Breakpoints" on the DM grid page? http://cfpb.github.io/design-manual/global-elements/grid.html
May need to refine the wording of that section. Also, we're defining <601 as XS on that page.

**Comment by jenn-franklin** [comment]
If we do include "<601 px" on this page instead of linking to the grid page, I feel like it needs a little more context, hmm.... like "screen size <601px"... Hate to be verbose but with the px of the type size and linespacing, there are a lot of pixels running around.

**Comment by nataliafitzgerald** [comment]
@huetingj 
I think we need to come up with a sentence or two to place at the top of "Web hierarchy" that talks about responsiveness and spells out the top level details of our system.

**Review by jenn-franklin — APPROVED** [review]

**Comment by nataliafitzgerald** [comment]
@huetingj @marteki 
I went ahead and updated the text in the "Web hierarchy" section to provide more specific information about the change in type sizes at 600 and below. 
screen shot 2018-02-21 at 5 49 15 pm

**Comment by nataliafitzgerald** [comment]
This one is ready to merge pending the Travis fix that @marteki is working on.

**Pull request merged**
