### PR TITLE
Added section on breakpoints to Grid

### PR DESCRIPTION
**Pull request by mebates**
Not sure if the link to 'view code' is correct

### CODE REVIEW

**Comment by mebates** [comment]
Did this break the grid column thing above it? Not sure why.

**Comment by Scotchester** [comment]
I think because you accidentally removed the `{:/nomarkdown}` from the line right before your additions.

**Comment by Scotchester** [comment]
Regarding the link to view the code, I think in this particular case, I would link to this: https://github.com/cfpb/cf-core/blob/gh-pages/src/cf-vars.less#L59-L66

What do you think, @jimmynotjim?

**Comment by jimmynotjim** [comment]
Agreed

**Comment by mebates** [comment]
Fixed grid thing and updated link!

**Comment by Scotchester** [comment]
:+1:

**Pull request merged**
