### PR TITLE
make the footer sticky closes #123

### LINKED ISSUE #123: Affix footer to bottom of browser window
For larger displays where the content doesn't fill the page. (Minor task)

screen shot 2014-04-16 at 11 54 04 am

### PR DESCRIPTION
**Pull request by ascott1**
screen shot 2014-04-22 at 7 11 16 am

### CODE REVIEW

**Comment by Scotchester** [comment]
Implementation looks solid :+1: 

Just one minor complaint: Switching `.footer` to `display: table-row` killed the top and bottom padding and things look a little scrunched now. Could you adjust that before we merge?

**Comment by ascott1** [comment]
Bah, I caught that in DOCter but not here. Will do.

**Comment by ascott1** [comment]
Updated!

**Comment by Scotchester** [comment]
Thank ya kindly!

**Comment by iuloshi** [comment]
Thanks guys!

**Pull request merged**
