### PR TITLE
Refactor front end

### LINKED ISSUE #256: Update front-end build process to current CF workflow
The Design Manual's front-end build process needs to be overhauled to follow the current recommended Capital Framework workflow.

This could potentially be a good small project for the fellowship immersion in January.

### PR DESCRIPTION
**Pull request by Scotchester**
This PR refactors the Design Manual front end. It is now based on the template provided by the Capital Framework [Yeoman generator](https://www.npmjs.com/package/generator-cf), and the structure will make it vastly easier to update as Capital Framework components get updated.

You can preview it at https://scotchester.github.io/design-manual/

Closes #256

### CODE REVIEW

**Comment by Scotchester** [comment]
Reviews would be appreciated from any of: @himedlooff @ascott1 @contolini

**Comment by Scotchester** [comment]
Probably needs a README update, as suggested by @mebates in #256.

**Comment by ascott1** [comment]
At first blush this is a huge improvement!

Can we make the footer sticky? It looks odd on short pages:

screen shot 2015-03-23 at 12 00 28 pm

That could roll into another pull request and doesn't need to hold this one up though.

**edit:** view the full size image to see what I mean.

**Comment by Scotchester** [comment]
Ah, we had done that before. I didn't test enough to notice that after the transition. Thanks for pointing it out!

**Comment by himedlooff** [comment]
Would be weird for me to review since I made a lot of the commits, right?

selfie-1

**Comment by Scotchester** [comment]
Hah, true ;)

**Comment by ascott1** [comment]
Running `npm install` & `bower install` leaves me with a modified capital-framework.less and cf-icons font files in the src directory. Should we ignore these files?

**Comment by ascott1** [comment]
Ok, I did a pretty thorough review of this this am. It's a huge improvement to work with the front end now. Nicely done @Scotchester and @himedlooff (ps we miss you).

Two things:
1. I think we do need to address the lack of the sticky footer before merging this. It looks really bad on short pages.
2. See my comment above about modified files with every npm/bower install.

Once those things are addressed, this is good to merge.

**Comment by jimmynotjim** [comment]
Instead of a sticky footer could you set the `body` bg color to 10% gray so it looks like the footer just takes up the rest of the page? Would be a lot simpler and less code to maintain.

**Comment by himedlooff** [comment]
@jimmynotjim, that's usually my go-to strategy for that. :+1:

**Comment by ascott1** [comment]
That could make for a giant footer on some of those pages... and we did already have the sticky footer. Either way, we need somethin'.

**edit** The above sounds cranky. Sorry. I mean, "if it looks good with the body by color thing, let's do it. Otherwise, let's reimplement the sticky footer."

**Comment by Scotchester** [comment]
> Running npm install & bower install leaves me with a modified capital-framework.less and cf-icons font files in the src directory. Should we ignore these files?

I'm fixing this here immediately, but this needs to be fixed upstream in generator-cf, too.

**Comment by Scotchester** [comment]
Ok, fixed Adam's two issues and even overhauled the README to make sure it matched with the new workflow :) I think this is ready for merge!

**Comment by ascott1** [comment]
:boom: Nicely done @Scotchester and @himedlooff!

**Comment by Scotchester** [comment]
Thanks!

**Pull request merged**
