### PR TITLE
Added data-viz nav item

### LINKED ISSUE #453: Add "Data visualization" as main nav / vertical

### PR DESCRIPTION
**Pull request by jimmynotjim**
Added the datavisualization item to the main navigtaion

## Changes

- Uncommented hidden data-viz nav item in the main nav.

## Testing

- Start the server and check the main nav

## Review

- @Scotchester 
- @caheberer 

[Preview this PR without the whitespace changes](?w=0)

## Screenshots

screen shot 2017-02-17 at 11 01 33 am

## Notes

- Fixes #453
- There is currently zero content on the page that was already set up. Not sure who's responsible for that.

## Todos

- Add content to the new page.
- Fill out the Sidebar nav as child pages are added.

## Checklist

* [x] Changes are limited to a single goal (no scope creep)
* [x] Code can be automatically merged (no conflicts)
* [x] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
* [x] Passes all existing automated tests
* [x] New functions include new tests
* [x] New functions are documented (with a description, list of inputs, and expected output)
* [x] Placeholder code is flagged
* [x] Visually tested in supported browsers and devices
* [x] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)

### CODE REVIEW

**Comment by Scotchester** [comment]
Uhhh, I'm going to revert this, because the page has no content yet.

**Comment by caheberer** [comment]
@Scotchester is this a large concern? If adding this nav item, or other small tweaks like this, allows someone to pick up the work from here, is there a reason that we can't have a blank page for a bit? I'm thinking any tiny bit of forward progress is better than none. But definitely interested in hearing your thoughts.

**Comment by Scotchester** [comment]
I'm not sure it's a _large_ concern, but it doesn't feel right to be pointing to a page that is literally blank, other than the title. 

Also, having the page in the navigation is not a prerequisite for being able to work on it. Since the file exists in the repo, anyone can navigate to `/data-visualization/data-visualization.html` and see the page.

**Comment by caheberer** [comment]
Gotchya. Makes sense.

**Comment by jimmynotjim** [comment]
The nav item was already there too, I just un-hid it.

**Pull request merged**
