### PR TITLE
Adding Hero and Featured content module to side nav

### PR DESCRIPTION
**Pull request by jenn-franklin**
## Additions

Added Hero and Featured content module to nav
## Changes

Changed page title from "Heroes" to "Hero"
## Review

@Scotchester
## Screenshots

screen shot 2016-01-05 at 1 29 12 pm

screen shot 2016-01-04 at 6 47 19 pm

### CODE REVIEW

**Comment by Scotchester** [comment]
Should the titles not be plural? The other pages use plural titles.

**Comment by jenn-franklin** [comment]
Yah, I went back and forth with this. I'll bring it up with the UX team as they're redoing the content guidelines. 

I noticed singular vs. plural because we had "Heroes" but then "Featured content module." And so it felt strange to have one singular and one plural in the nav. Then I started thinking about how there is only one type of hero now. Originally, we thought there would be a hero and a super hero (or something like that). But now we only have one type, and then you can customize it (with things like including a CTA or not, etc.). Versus, with something like buttons there are variations, such as the large primary button. But then I felt like my reasoning was whack. Because then should a category like "Color" technically be "Colors?" And what exactly does "variation" mean?

I also realized that writing the content of the page as plural doesn't really make sense. So, "Featured content modules (FCMs) function to highlight a specific piece of content within a page." FCM is plural but page is singular. And within a single page, you will only have one FCM. And you only have one FCM design available for use.

So, I probably should leave this to UX people. Perhaps for the time being, I'll actually make the opposite change: Keep as "Heroes" and change to "Featured content modules." This way the content as written currently in the plural form on the pages matches the titles. And we can give it a little more thought as the new guidelines are being written. 

Update to pull request coming momentarily.

**Comment by Scotchester** [comment]
Sounds good. I was just observing that, in this section at least, all the pages are plural: buttons, expandables, form fields, etc.

But yeah, I think the content overhaul will probably take care of it :)

**Comment by Scotchester** [comment]
Your `hero.md` file is still kicking around. Mind deleting that before we merge?

**Comment by jenn-franklin** [comment]
Oh whoops gross. I deleted it!

**Comment by benguhin** [comment]
Agreed that it's best to deal with all of the things at once in the content overhaul. For now, you can also go with "Hero sections," which sounds a lot less like a TV show

**Comment by Scotchester** [comment]
@benguhin :laughing: Not a bad suggestion, but I'm going to go ahead and merge now :)

**Comment by jenn-franklin** [comment]
Haha @benguhin :smile: Love it. Thanks, @Scotchester!

**Pull request merged**
