### PR TITLE
Adds topdoc task and template for creating icon markup partials from capital framework topdoc comments.

### PR DESCRIPTION
**Pull request by himedlooff**
This sets us up for converting the data stored within Capital Framework Topdoc comments into HTML partials that can be used as Jekyll includes. We will probably need a template for each ui-type since the markup for displaying it here in the design manual might be different for each type. I have only set up the icons, more templates will need to be made but let's first see if this is working out.

### CODE REVIEW

**Comment by himedlooff** [comment]
Hold off on merging this. It's not outputting what i expected.

**Comment by himedlooff** [comment]
Ok all good.

**Comment by Scotchester** [comment]
Is this not actually being output anywhere yet?

**Comment by himedlooff** [comment]
It generated `_includes/ui-toolkit/icons/index.html` which has not been added to any page yet.

**Comment by iuloshi** [comment]
Hey thanks so much @himedlooff for taking this on!! :+1: :smiley_cat:

**Pull request merged**
