### PR TITLE
clarify about padding, change max-width to 1230

### PR DESCRIPTION
**Pull request by benguhin**
Based on decision to use 1170 as max width for content plus 30px on each side

Also clarifying that padding amounts are _total_ amounts

@Scotchester @mebates

### CODE REVIEW

**Comment by benguhin** [comment]
@Scotchester I support however you think it should be worded – I just created this PR during the meeting so that I could say "Pull request sent!"

**Comment by Scotchester** [comment]
Ok, I'll update it :)

**Comment by mebates** [comment]
woof, I just redid this in another pull request since I didn't know this was open. (but I think mine is more accurate?) let's try to clear these pull requests out!

**Comment by Scotchester** [comment]
Superseded by #350.

**Pull request closed without merging**
