### PR TITLE
Update color-principles.md

### PR DESCRIPTION
**Pull request by ell0ell0**
Updated the primary colors

### CODE REVIEW

**Comment by Scotchester** [comment]
Note: This is not quite ready for merging.

**Comment by mebates** [comment]
thanks @ell0ell0! :+1:

**Comment by Scotchester** [comment]
Awesome, thanks! Merging now.

**Comment by mebates** [comment]
Yo guys - Is it missing Navy 50%?

**Comment by Scotchester** [comment]
Yeah, it is.

**Pull request merged**
