### PR TITLE
Format intro and sections for Isocons, Minicons, Logo, Beams, and Color

### PR DESCRIPTION
**Pull request by ohsk**
Still a lot of placeholder images for some sections, as well as a need for more advanced formatting.

### CODE REVIEW

**Comment by ohsk** [comment]
Hello, internet?

**Comment by stephanieosan** [comment]
On the logo page, are there supposed to be numbers next to the content under "Examples of Misuse"? If yes, they should be changed to not all be "1." If no, they should be removed.

screen shot 2014-03-27 at 5 27 28 pm

**Comment by ohsk** [comment]
Mmm, we have them numbered in the Style Guide, but that's really more for keying them to the caption at the bottom of the page. Not really necessary here.

image
image

**Comment by ohsk** [comment]
Ok, pushed through a removal of the numbering. The Logo page in particular needs a lot more updating in terms of structure / format for the image assets; I was really just focused on getting as many of the headers and intro sections up to speed in .md.

**Pull request merged**
