### PR TITLE
Add web subheader example

### PR DESCRIPTION
**Pull request by Scotchester**
Preview on my fork: http://scotchester.github.io/design-manual/identity/typography.html#web-hierarchy

### CODE REVIEW

**Comment by benguhin** [comment]
I can't wait till @scotchester updates the capital framework css!

**Comment by mebates** [comment]
Thanks for helping out @Scotchester!

**Comment by Scotchester** [comment]
Awaiting cfpb/cf-core#34

**Comment by Scotchester** [comment]
Ok, this is ready for final review! Please see the link to my fork in the original post to verify. @mebates

**Comment by mebates** [comment]
On your fork, the subheader example displays in Georgia, not Avenir.

screen shot 2015-05-11 at 1 33 44 pm

**Comment by Scotchester** [comment]
What the heck? :confused: It worked fine locally.

**Comment by mebates** [comment]
Sorry. What's the next step? Can someone help, or something I can do?

**Comment by Scotchester** [comment]
I just need to find a few minutes to troubleshoot it. Shouldn't take long.

**Comment by mebates** [comment]
We stalled on this! Any solution ready by Monday for the meeting, @Scotchester ?

**Comment by Scotchester** [comment]
You know, I actually started back in on this earlier today before inevitably getting distracted. Let me see if I can crank it out before the end of the day.

**Comment by Scotchester** [comment]
Ok! Should be fixed. Take another look.

**Comment by mebates** [comment]
zomg! merging this.

**Pull request merged**
