### PR TITLE
Adjust layout widths, add sample content page and add blank pages for UI toolkit pages.

### PR DESCRIPTION
**Pull request by davidakennedy**

### CODE REVIEW

**Comment by ascott1** [comment]
Looking good @davidakennedy! My only question is why `design-manual.min.css` isn't actually minified https://github.com/davidakennedy/design-manual/blob/gh-pages/assets/css/design-manual.min.css

**Comment by davidakennedy** [comment]
Dang! Good catch! Think I forgot to run Grunt before this commit. Will fix.

**Comment by davidakennedy** [comment]
So now I've:
- added [CSSMin](https://github.com/gruntjs/grunt-contrib-cssmin) task
- Tasks create an unminified CSS file, helpful for development and a minified one for production
- Removed `main.css`, leftover from DOCtor.

**Comment by ascott1** [comment]
:boom: nicely done

**Pull request merged**
