### PR TITLE
Add "Owning a home" to Isocons > Asset Library

### PR DESCRIPTION
**Pull request by ohsk**
Per issue #94

### CODE REVIEW

**Comment by ohsk** [comment]
Also added a few images for Typography > Typesetting section. Still have to add new content for **Line length** and **Spacing**.

**Comment by Scotchester** [comment]
Thanks, @ohsk! Be sure to comment again when you've finished adding that content, since notifications don't come in for new commits.

Also, the new house isocon is intended to replace the existing Mortgage "sold" sign isocon, right?

**Comment by ohsk** [comment]
No prob! I've finished the content for the [Typesetting section](http://ohsk.github.io/design-manual/identity/typography.html) now, let me know if you guys see any suggested tweaks.

Re: Owning a home isocon, I know this was an update of the old one, but I'm inclined to think we should keep the Mortgage one just in case? @stephanieosan, do you know what the game plan was? I still have the Mortgage "for sale sign" in the Illustrator library set...

**Comment by ohsk** [comment]
(Also, this addresses some of the content tasks noted in Issue #77)

**Comment by ohsk** [comment]
@Scotchester, spoke with @nataliafitzgerald and replacing the Mortgage isocon with the new house seems to be the way to go! I think this should do for the latest batch of content edits to the Identity pages.

**Comment by iuloshi** [comment]
Thanks @ohsk! Looks great! :+1:

**Comment by Scotchester** [comment]
Thanks!

**Pull request merged**
