### PR TITLE
Updates to the hero and FCM DM pages

### PR DESCRIPTION
**Pull request by jenn-franklin**
## Changes

Updated guidelines to reflect 15px spacing after the heading at all screen sizes. Updated example visuals to show this. 
## Review

@Scotchester @nataliafitzgerald 
## Screenshot

hero_page

### CODE REVIEW

**Comment by jenn-franklin** [comment]
I committed changes to the FCM guidelines page today. I apologize for not making all of my commits to both the hero and FCM pages before submitting this pull request. Here are the changes made to the FCM page:

## FCM Changes

Updated to reflect changes made during the development process: the height of the module, size/ratio of the image, spacing after the heading, image behavior at 700px. Updated visual examples to show these changes. Changed the headline size on mobile to be H3 instead of H2, which was a typo.

## Screenshot

featured content module cfpb design manual

**Comment by Scotchester** [comment]
Thanks! :+1:

**Comment by mebates** [comment]
Is there anything preventing us from adding these new pages into the nav?

**Comment by Scotchester** [comment]
I don't think so!

**Comment by jenn-franklin** [comment]
Thank you! No reservations from me.

**Comment by jenn-franklin** [comment]
Actually— I'm going to follow up with @jimmynotjim to double check that everything is good to go. Will post again here when ready.

**Comment by jimmynotjim** [comment]
Ditto my [comment in 384](https://github.com/cfpb/design-manual/issues/348#issuecomment-168060505). We should be good to go.

**Comment by jenn-franklin** [comment]
:+1:

**Comment by stephanieosan** [comment]
So, are we adding this into the nav in a different pull request, or did that already happen and I missed it?

And if we need to submit a different pull request to add it into the nav, who is up for doing that?

**Comment by jenn-franklin** [comment]
It hasn't happened. I'll add it to the nav and submit a PR. (Or I'll reach out to @Scotchester if I discover I don't know what I'm doing.)

**Comment by Scotchester** [comment]
Thanks, @huetingj!

**Comment by jenn-franklin** [comment]
Pull request here: #385 @Scotchester @stephanieosan

**Pull request merged**
