### PR TITLE
Updates the project assets to use the latest release from Capital Framework.

### PR DESCRIPTION
**Pull request by jimmynotjim**
Updates the project to use the latest release from Capital Framework.

## Changes

- ~~Updates cf-expandables v7.0.0~~
- ~~Updates cf-atomic-component to v2.0.0~~
- ~~Updates cf-tables to v5.0.0~~
- Adds initialization code for cf-expandables and cf-tables.
- Regenerates assets with `grunt`.

(Added by Ans)

## Testing

- Run `npm start`
- Open http://localhost:4000/page-components/expandables.html and make sure the expandables continue to work
- Open http://localhost:4000/page-components/tables.html and make sure the tables continue to work

## Notes

We'll need decide what to do about accordions documentation. Turns out they are necessary for the OaH explanations, but I don't know how much we want to encourage their use outside of those pages. The simplest answer is to probably revert this change https://github.com/cfpb/design-manual/commit/bb035a7ca5245d8093bcda54b3269044e28fe331#diff-7c1ba7f64a56bc337d12c911525c729f but I'll leave that up to the design team.

### CODE REVIEW

**Comment by Scotchester** [comment]
The dependency versions in `package.json` don't match what you're saying in the PR.

**Comment by jimmynotjim** [comment]
@Scotchester thanks for catching that, not sure what I was doing, fixed it though.

**Comment by jimmynotjim** [comment]
@Scotchester blah, I completely forgot to ping you about this one before I left. You may want to run it locally and make sure I updated and rebuilt correctly the second time before merging. 🎩

**Comment by Scotchester** [comment]
@jimmynotjim No worries, I haven't forgotten it, just been busy :)

**Comment by jimmynotjim** [comment]
😢 Sooooo lonely....

**Review by marteki — APPROVED** [review]

**Comment by Scotchester** [comment]
Please hold. I want to release the couple patches that are merged and then update this PR.

**Comment by anselmbradford** [comment]
This may be superseded by https://github.com/cfpb/design-manual/pull/618

**Comment by jimmynotjim** [comment]
Couldn't give me my last contribution huh Ans 😜 Hope y'all are doing well. Good to see this project getting some love again.

**Comment by anselmbradford** [comment]
@jimmynotjim You could get that sweet sweet reviewer cred on https://github.com/cfpb/design-manual/pull/618! 😝

**Review by cfarm — APPROVED** [review]
expandables and tables are back 💯

**Review by virginiacc — APPROVED** [review]

**Comment by anselmbradford** [comment]
And @jimmynotjim gets his credit after all 😄

**Comment by cfarm** [comment]
YAYY @jimmynotjim lives!

**Comment by jimmynotjim** [comment]
Huzzah!!!

https://media.giphy.com/media/vl8ncD72EnhoA/giphy.gif

**Pull request merged**
