### PR TITLE
Update project to use capital framework v1.x.x

### PR DESCRIPTION
**Pull request by cfarm**
Fixes Less compiling on this project and upgrades to use Capital Framework v1.x.x, removes dependency on grunt concat task. Based on https://github.com/cfpb/cfgov-refresh/pull/608

This is needed to continue work on #346 
## Removals
- some commented out stuff on form fields page
- concat task for cf-less which concatenated capital framework files
## Changes
- update bower dependency to capital framework ~1.0.0
- update main.less to point to capital-framework.less file
## Testing
- check out branch
- run npm install, grunt
## Review
- @Scotchester 
## Checklist
- [x] Changes are limited to a single goal (no scope creep)
- [x] Code can be automatically merged (no conflicts)
- [x] Code follows the standards laid out in the [front end playbook](https://github.com/cfpb/front-end)
- [ ] Passes all existing automated tests
- [ ] New functions include new tests
- [ ] New functions are documented (with a description, list of inputs, and expected output)
- [ ] Placeholder code is flagged
- [ ] Visually tested in supported browsers and devices 
- [ ] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)

### CODE REVIEW

**Comment by KimberlyMunoz** [comment]
:+1:

**Comment by jimmynotjim** [comment]
:+1: I'm ok with this is @Scotchester is. I only pinned the versions because of his concerns brought up in cfgov-refresh #608 and this project is monitored far less than that one.

**Comment by cfarm** [comment]
tested by @KimberlyMunoz and it works without the bug from @jimmynotjim's - @Scotchester please to merge!

**Comment by Scotchester** [comment]
So here's the thing.

If I pull down a fresh clone of your repo, switch to the `cf-v1` branch, run `npm install` and `grunt`, I get no changes. This is good.

If I update my existing local clone's gh-pages branch with the latest from upstream, then run GitHub's recommended steps for starting a manual merge:

``` sh
git checkout -b cfarm-cf-v1 gh-pages
git pull https://github.com/cfarm/design-manual.git cf-v1
```

Then run `npm install` and `grunt`, I get changes on 6 files in `/static/css` and `/static/js`.

I don't get it. What are we missing? Is it just something we have to deal with once and then it'll be fine from there on out? Or will it happen every time someone tries to update their local clone?

**Comment by Scotchester** [comment]
I just did a test with a fresh clone of cfpb/design-manual, then following the first step of GH's manual merge directions.

This time, after running `grunt`, no changes.

This leads me to suspect that the problem with trying to do it in an existing local clone is maybe some kind of Bower caching issue.

**Comment by Scotchester** [comment]
Ah, this is great. Just tried another fresh clone of cfpb/design-manual, and found it couldn't even be set up correctly. :rage1: Something in the Less paths is wacky.

Gotta go for tonight, but will keep investigating tomorrow.

**Comment by cfarm** [comment]
@Scotchester your last comment is the same problem I had first setting up the project. This branch fixes it for me, though - it's the reason I made this change.

**Comment by Scotchester** [comment]
The problem I still have is that I can't merge this code into my current local clone and get it to work (i.e., not show changes in the build files). I'd like to avoid making everyone do fresh clones after this is merged.

After encountering similar weirdness on an unrelated project, I think the problem we have is dependency caching/conflicts. We should add a `setup.sh` script to this repo so we can have people fetch the new code, run the script to blow away all the old junk, and start fresh.

**Comment by cfarm** [comment]
So your problem with this PR is that it shows diffs in the compiled files? 

If there's a solution I'm happy to help. In the meantime we are blocked from proceeding with design manual work on my team because designers need to be able to compile the CSS locally to see my Capital Framework styles in progress while they are updating the content. Right now, they can only update the content and aren't able to see any new CSS compiled due to the less bug you and I both encountered.

**Comment by Scotchester** [comment]
Yeah, it's the same basic issue I had with Jimmy's. In theory, once this is merged into an existing repo, running Grunt should not change the built files. They should be exactly the same as what they are after the merge. Shouldn't they?

If this is blocking your work, I guess we should bite the bullet. Making folks re-clone is probably quicker than getting `setup.sh` in place. Just make sure your team deletes their current clone and re-clones. (Don't lose whatever local changes may have been made.) We need everyone to be working from the same exact dependencies, or the built files will constantly be getting changed based on who last compiled, even if nothing was changed in the Less or JS source.

Sound good?

**Comment by cfarm** [comment]
sounds good!

**Comment by cfarm** [comment]
So I just realized that this PR seems to make web fonts not work - see

https://cfpb.github.io/design-manual/index.html

and 

http://cfarm.github.io/design-manual/

Any ideas why this happened?

**Comment by KimberlyMunoz** [comment]
Capital Framework ships with default fonts by default, we need to add the custom fonts by overwriting the variables for webfonts. 

https://github.com/cfpb/cf-core/blob/gh-pages/src/cf-base.less#L38

**Comment by cfarm** [comment]
Ah, thanks! So I can just copy what Flapjack has here? https://github.com/cfpb/cfgov-refresh/blob/flapjack/src/static/css/cf-theme-overrides.less#L21-L26

**Comment by KimberlyMunoz** [comment]
Yep! I forgot all about that in this PR.

**Pull request merged**
