### PR TITLE
Adjust headings for accessibility guide for better structure.

### PR DESCRIPTION
**Pull request by davidakennedy**
Partially addresses #179.

### CODE REVIEW

**Comment by Scotchester** [comment]
Shall we hold merging until you do the other things you wanted to do for #179?

**Comment by davidakennedy** [comment]
There you go: updated. See: http://davidakennedy.github.io/design-manual/guides/accessible-interfaces.html

**Comment by iuloshi** [comment]
Thanks @davidakennedy! 

I understand from a semantic point of view why you changed the headers in the hierarchy so they cascade chronologically from H1, H2, H3, etc, but could we style them as currently reflected on the [Design Manual](http://cfpb.github.io/design-manual/guides/accessible-interfaces.html), i.e. bumped down one level on the type hierarchy? That way it will remain consistent with the other guides.

Also for the links to the W3C site, could we capitalize each of the section names in the external links? So for example, "View Perceivable on W3C site", since "Perceivable" is the title of the section.

**Comment by Scotchester** [comment]
**Please hold for merging** until #228 has been merged.

**Comment by davidakennedy** [comment]
This PR also adds some JS to create a text alternative for the external link icon.

Also, @iuloshi see: http://davidakennedy.github.io/design-manual/guides/accessible-interfaces.html

Updated the visual hierarchy.

**Comment by iuloshi** [comment]
:+1: Thanks @davidakennedy!

**Comment by Scotchester** [comment]
Thanks, @davidakennedy!

**Pull request merged**
