### PR TITLE
Add markup and styling for Typography diagrams

### PR DESCRIPTION
**Pull request by Scotchester**

### CODE REVIEW

**Comment by ascott1** [comment]
@Scotchester Just a heads up.... This PR can't be automatically merged. I'm going to take a look at @danny8000's PR and then will likely merge it in, so you may want to hold off on fixing conflicts until after that.

**Comment by Scotchester** [comment]
Hmm, not sure why that's true without merging #42, but probably because I did this with no connection on a plane and couldn't make sure I was up to date :) In any case, I'm also perusing that PR. Once it gets merged, I'll deal with this one.

**Comment by ascott1** [comment]
Reviewed the code and saw @Scotchester's working design and it all looks great. Once the conflict is fixed this is ready to merge.

**Comment by Scotchester** [comment]
Yay, mergeable!

**Pull request merged**
