### PR TITLE
Closes #215 & #203

### LINKED ISSUE #215: H6 on Print Typography Hierarchy example is incorrect
Avenir Medium 14/16 pt is correct. The example to the right is not; should be larger and not all caps.

### PR DESCRIPTION
**Pull request by iuloshi**
- Deleted PDF Style Guide from Identity page
- Fixed print type hierarchy examples
- Added note to footer about our latest standards

@scotchester I deleted my original, re-forked, and made the changes, but that margin bug returned when I ran `grunt` I think. :frowning: 

http://iuloshi.github.io/design-manual/

### CODE REVIEW

**Comment by Scotchester** [comment]
Argh, sorry, I think I broke that. I can explain how, if you want, but I just pushed a hotfix to this repo. If you pull from upstream and then push to your origin again, we should be good to go.

**Comment by iuloshi** [comment]
@Scotchester All clear & ready for merging! Thanks.

**Comment by Scotchester** [comment]
And... I forgot to tell you you'll need to re-run Grunt. Sorry!

**Comment by iuloshi** [comment]
Woops! Okay all good now: http://iuloshi.github.io/design-manual/

**Comment by Scotchester** [comment]
Excellent; thanks!

**Pull request merged**
